### ISSUE TITLE
Getting the spreadsheet form definition xlsx file

### ISSUE THREAD

**Issue by Lakelagoon** [IDinsight/surveycto-python#1]
Is there a way to get the last spreadsheet form definition xlsx file using pysurveycto?
I want to make the usual stata job in python.

Thanks a lot pysurveycto is great!

**Comment by jeenut27** [comment]
Hi, 
We can add a function to pysurveycto to get the form definition data. This will be a very useful feature to have. So we are working on it. Thanks for raising the issue!
