### ISSUE TITLE
Variable "key" undefined on row 363 in method "__check_json_extraction_params"

### ISSUE THREAD

**Issue by TheOmnimax** [IDinsight/surveycto-python#3]
Hi, this is Max of SurveyCTO support. A user attempted to use this module, but came across an error, and I believe I know the issue: On row 363, it makes this method call:

    self.__check_key_and_raise(key)

However, while the "key" parameter is defined in many of the methods in that class, it is not defined in the "__check_json_extraction_params" method. This is causing an error when it calls for that variable on row 363. Let me know if you need more details. Thanks!

**Comment by edodge** [comment]
Thanks for raising this @TheOmnimax! I've opened a pull request that should fix the issue.

@jeenut27 Please review the PR and redeploy the package if the code fix looks good to you.

**Comment by jeenut27** [comment]
Hi, the PR's merged in and deployed. The new package version is `0.0.12`.

**Comment by TheOmnimax** [comment]
@jeenut27 Thanks, it looks like it has been fixed! The user has installed the new version, and that is working well.
