### ISSUE TITLE
Invalid date string

### ISSUE THREAD

**Issue by TheOmnimax** [IDinsight/surveycto-python#5]
On [row 268](https://github.com/IDinsight/surveycto-python/blob/master/pysurveycto/pysurveycto.py#L268), there is an invalid date string template:
```
url_date = quote(oldest_completion_date.strftime("%b %-d, %Y %-I:%M:%S %p"))
```
This is causing errors when a date is being specified.

While I'm not 100% sure on this, is it supposed to return a Unix time code? That is what is needed for the [SurveyCTO REST API](https://support.surveycto.com/hc/en-us/articles/360033156894-REST-API-documentation). Thanks!

**Comment by jeenut27** [comment]
Hi @TheOmnimax, 

`oldest_completion_date` is a Python `datetime.date` or `datetime.datetime` object and `url_date` is the URL encoded value of the date.

For example: if the date is 24 November, 2021 13:42:42:
```
import datetime
from urllib.parse import quote

oldest_completion_date = datetime.datetime(2021, 11, 24, 13, 42, 42)
url_date = quote(oldest_completion_date.strftime("%b %-d, %Y %-I:%M:%S %p"))

# oldest_completion_date.strftime("%b %-d, %Y %-I:%M:%S %p")  is  'Nov 24, 2021 1:42:42 PM'
# url_date is 'Nov%2024%2C%202021%201%3A42%3A42%20PM'
```

Could you give an example where this is giving an error?

**Comment by TheOmnimax** [comment]
@jeenut27 I have reached out to the user who reported this issue to ask if they can share their code.

**Comment by TheOmnimax** [comment]
@jeenut27 I have been doing some testing, and while I cannot replicate the issue on my MacOS computer, I can on my Windows computer, so I believe that is the issue. It looks like those hyphens in the date string template are not supported on Windows.

**Comment by edodge** [comment]
Thanks for looking into this @TheOmnimax.

[This reference](https://strftime.org/) shows the codes that are platform-specific, which confirms that codes with hyphens are not supported on Windows. Interestingly, it looks like the hyphen can be replaced with a hash on Windows.

Max, could you confirm that the hash works on your windows computer?

@jeenut27 assuming the above works should we just add a try/except block to deal with this? Or we can check if the OS is Windows as shown [here](https://stackoverflow.com/a/1325587).

**Comment by jeenut27** [comment]
Yes, adding try/except block to handle this makes sense to me! I will update the code and create a PR.

**Comment by jeenut27** [comment]
Hi @TheOmnimax ,
We added in a try/except block to handle the timestamps using `-` and `#` in case `-` fails. The upgraded `pysurveycto` version is `0.0.13`. Please let us know if you still get the same issue!
