### ISSUE TITLE
Old columns get dropped after a significant change in the form structure.

### ISSUE THREAD

**Issue by rahulm-cms** [IDinsight/surveycto-python#8]
Hey,
I had to make some serious changes to the form where I had to move certain columns into groups. I had expected that with the API call, I'd get the data such that the old columns remain, but the same columns (now in a group) would be added as new columns. However, the old columns get dropped and the old data is not in the new column either. Is there a parameter I'm missing. Please do let me know. Cheers.
P.S. Love the work you've done so far!

**Comment by jeenut27** [comment]
Hi, 
To get the columns from all versions of a SurveyCTO form, you will need to export the data is JSON format. CSV export by default only returns the columns which are there in the latest form definition and there is no option provided to change that behaviour. 
For JSON export, add a parameter `format="json"` in the function call like:`scto.get_form_data(form_id, format="json")`. 

Do let us know if this works! And so glad to know that you are finding this library useful! Thanks.

**Comment by edodge** [comment]
And to be clear the issue here is how the SurveyCTO API is implemented in regard to csv vs json data export, not how the library is implemented

**Comment by rahulm-cms** [comment]
Hey,
I tried using the JSON format initially (I wanted the my data in long format since I had a bunch of repeat groups) but I ran into two issues.
1. Data still came in wide format irrespective of the value of the attribute I specified.
2. The API has a limit on the number of times I could pull the data and only in wide format.
Pretty much off-set both these issues using the csv format.
